import type { Metadata } from "next";
import "./globals.css";
import { roobert } from "@/fonts/fonts";

export const metadata: Metadata = {
  title: "Claim Your PCP",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en-GB">
      
      <body className={`${roobert.className}`}>{children}</body>
    </html>
  );
}
