import type { Metadata } from "next";
import "./globals.css";
import { roobert } from "@/fonts/fonts";

export const metadata: Metadata = {
  title: "Claim Your PCP",
  description: "Generated by create next app",
  keywords: "",
  robots: "follow, index",
  openGraph: {
    title: "Claim Your PCP",
    description: "Generated by create next app",
    images: [
      { url: "https://carfinancesolicitors.co.uk/images/opengraph.png" },
    ],
    url: "https://carfinancesolicitors.co.uk",
    siteName: "Claim Your PCP",
    locale: "en-GB",
    type: "website",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en-GB">
      <head>
        <link rel="canonical" href="https://carfinancesolicitors.co.uk" />
        <link rel="icon" href="/favicon.ico" sizes="any" />
      </head>
      <body className={`${roobert.className}`}>{children}</body>
    </html>
  );
}
