export const options = [
  {
    value: "Select a finance provider",
    label: "Select a finance provider",
    isDisabled: true,
  },
  { value: "1st Stop Car Finance", label: "1st Stop Car Finance" },
  { value: "1st Stop Finance", label: "1st Stop Finance" },
  { value: "24 Studio", label: "24 Studio" },
  { value: "247 Money Group Limited", label: "247 Money Group Limited" },
  { value: "A1 Mortgages", label: "A1 Mortgages" },
  { value: "ACF Car Finance Limited", label: "ACF Car Finance Limited" },
  { value: "ALD Automotive", label: "ALD Automotive" },
  { value: "ALD Automotive Limited", label: "ALD Automotive Limited" },
  {
    value: "Admiral Financial Services Ltd",
    label: "Admiral Financial Services Ltd",
  },
  { value: "Advantage  Finanace", label: "Advantage  Finanace" },
  { value: "Advantage Finance", label: "Advantage Finance" },
  {
    value: "Advanced Payment Solutions Limited",
    label: "Advanced Payment Solutions Limited",
  },
  { value: "Aqua Finance", label: "Aqua Finance" },
  { value: "Arnold Clarke Finance Ltd", label: "Arnold Clarke Finance Ltd" },
  { value: "Asda Money", label: "Asda Money" },
  { value: "Audi Finance", label: "Audi Finance" },
  {
    value: "Auto Accept Finance Limited",
    label: "Auto Accept Finance Limited",
  },
  { value: "Auto Union Finance", label: "Auto Union Finance" },
  {
    value: "AutoBank Financial Services",
    label: "AutoBank Financial Services",
  },
  { value: "AutoMoney Limited", label: "AutoMoney Limited" },
  { value: "AutoMoney Motor Finance", label: "AutoMoney Motor Finance" },
  { value: "Barclays Bank UK Plc", label: "Barclays Bank UK Plc" },
  { value: "Barclays Partner Finance", label: "Barclays Partner Finance" },
  { value: "Bank Of Scotland plc", label: "Bank Of Scotland plc" },
  { value: "Billing Finance", label: "Billing Finance" },
  { value: "Billing Finance Limited", label: "Billing Finance Limited" },
  { value: "Black Horse", label: "Black Horse" },
  { value: "Blue Motor Finance Ltd", label: "Blue Motor Finance Ltd" },
  { value: "BMW Finance", label: "BMW Finance" },
  {
    value: "BMW Financial Services (GB) Limited",
    label: "BMW Financial Services (GB) Limited",
  },
  { value: "Bristol St Group Ltd", label: "Bristol St Group Ltd" },
  {
    value: "Burnley Savings and Loans Limited",
    label: "Burnley Savings and Loans Limited",
  },
  { value: "CA Auto Finance UK Ltd", label: "CA Auto Finance UK Ltd" },
  { value: "Car Land of Wolverhampton", label: "Car Land of Wolverhampton" },
  { value: "Carfinance247 Limited", label: "Carfinance247 Limited" },
  { value: "Carland of Wolverhampton", label: "Carland of Wolverhampton" },
  { value: "Citroen Financial Services", label: "Citroen Financial Services" },
  { value: "Close Brothers Limited", label: "Close Brothers Limited" },
  { value: "Close Motor Finance", label: "Close Motor Finance" },
  {
    value: "Clydesdale Financial Services Limited",
    label: "Clydesdale Financial Services Limited",
  },
  { value: "Conister Bank Limited", label: "Conister Bank Limited" },
  { value: "Creation Consumer Finance", label: "Creation Consumer Finance" },
  { value: "Decidebloom Limited", label: "Decidebloom Limited" },
  {
    value: "FCA Automotive Services Ltd",
    label: "FCA Automotive Services Ltd",
  },
  {
    value: "FCA Automotive Services UK Ltd",
    label: "FCA Automotive Services UK Ltd",
  },
  { value: "Family Finance Limited", label: "Family Finance Limited" },
  {
    value: "Fiat Auto Financial Services Ltd",
    label: "Fiat Auto Financial Services Ltd",
  },
  { value: "FirstRand Bank Ltd", label: "FirstRand Bank Ltd" },
  { value: "FirstRand Bank Limited", label: "FirstRand Bank Limited" },
  { value: "FGA Capital UK Ltd", label: "FGA Capital UK Ltd" },
  { value: "Fortis Lease", label: "Fortis Lease" },
  { value: "GE Capital", label: "GE Capital" },
  { value: "GE Money", label: "GE Money" },
  { value: "Go Car Credit Ltd", label: "Go Car Credit Ltd" },
  { value: "Hartwell Ford", label: "Hartwell Ford" },
  { value: "Hartwell Kidlington Ford", label: "Hartwell Kidlington Ford" },
  { value: "Hitachi Capital", label: "Hitachi Capital" },
  {
    value: "Hyundai Car Finance Limited",
    label: "Hyundai Car Finance Limited",
  },
  { value: "Hyundai Capital UK Ltd", label: "Hyundai Capital UK Ltd" },
  { value: "ING Lease (UK) Limited", label: "ING Lease (UK) Limited" },
  {
    value: "International Motors Finance Limited",
    label: "International Motors Finance Limited",
  },
  {
    value: "J.D. Williams & Company Limited",
    label: "J.D. Williams & Company Limited",
  },
  { value: "Kia Finance", label: "Kia Finance" },
  { value: "Land Rover Finance", label: "Land Rover Finance" },
  { value: "LeasePlan Finance Limited", label: "LeasePlan Finance Limited" },
  { value: "Lloyds Banking Group", label: "Lloyds Banking Group" },
  { value: "Lombard Bank Limited", label: "Lombard Bank Limited" },
  { value: "Lombard North Central", label: "Lombard North Central" },
  {
    value: "Mann Island Finance Limited",
    label: "Mann Island Finance Limited",
  },
  { value: "Marsh Finance Ltd", label: "Marsh Finance Ltd" },
  {
    value: "Mercedes-Benz Financial Services UK Limited",
    label: "Mercedes-Benz Financial Services UK Limited",
  },
  {
    value: "MG Financial Services GB Ltd",
    label: "MG Financial Services GB Ltd",
  },
  { value: "MI Vehicle Finance Limited", label: "MI Vehicle Finance Limited" },
  {
    value: "Mitsubishi HC Capital UK Plc",
    label: "Mitsubishi HC Capital UK Plc",
  },
  { value: "Moneybarn No. 1 Limited", label: "Moneybarn No. 1 Limited" },
  { value: "Morgan Stanley", label: "Morgan Stanley" },
  { value: "NIIB Group Ltd", label: "NIIB Group Ltd" },
  {
    value: "Nissan Finance (GB) Limited",
    label: "Nissan Finance (GB) Limited",
  },
  { value: "Northridge Finance", label: "Northridge Finance" },
  { value: "Norwich Union", label: "Norwich Union" },
  {
    value: "Oodle Financial Services Limited",
    label: "Oodle Financial Services Limited",
  },
  { value: "Oplo CF Ltd", label: "Oplo CF Ltd" },
  { value: "Paragon Banking Group PLC", label: "Paragon Banking Group PLC" },
  { value: "Paragon Personal Finance", label: "Paragon Personal Finance" },
  { value: "PCF Bank Limited", label: "PCF Bank Limited" },
  { value: "Peugeot Financial Services", label: "Peugeot Financial Services" },
  { value: "Penrican Credit Limited", label: "Penrican Credit Limited" },
  { value: "Perrys Vauxhall", label: "Perrys Vauxhall" },
  { value: "Premium Plan Limited", label: "Premium Plan Limited" },
  {
    value: "Private & Commercial Finance Group plc",
    label: "Private & Commercial Finance Group plc",
  },
  { value: "Raphaels Bank", label: "Raphaels Bank" },
  { value: "Ratesetter Motor Limited", label: "Ratesetter Motor Limited" },
  {
    value: "RCI Financial Services Limited",
    label: "RCI Financial Services Limited",
  },
  {
    value: "Renault - RCI Financial Services Limited",
    label: "Renault - RCI Financial Services Limited",
  },
  { value: "Retail Money Market Ltd", label: "Retail Money Market Ltd" },
  { value: "Secure Trust Bank", label: "Secure Trust Bank" },
  {
    value: "Secure Trust Bank Public Limited Company",
    label: "Secure Trust Bank Public Limited Company",
  },
  { value: "SEAT Finance", label: "SEAT Finance" },
  { value: "Shogun Finance Ltd", label: "Shogun Finance Ltd" },
  { value: "Suzuki Finance GB Ltd", label: "Suzuki Finance GB Ltd" },
  {
    value: "Suzuki Financial Services Limited",
    label: "Suzuki Financial Services Limited",
  },
  {
    value: "Suzuki Financial Services Limited",
    label: "Suzuki Financial Services Limited",
  },
  {
    value: "Tandem Motor Finance Limited",
    label: "Tandem Motor Finance Limited",
  },
  {
    value: "The Car Finance Company Ltd",
    label: "The Car Finance Company Ltd",
  },
  { value: "The Funding Corporation", label: "The Funding Corporation" },
  { value: "Toyota Financial Services", label: "Toyota Financial Services" },
  { value: "Vauxhall Finance plc", label: "Vauxhall Finance plc" },
  { value: "Vehicle Credit Limited", label: "Vehicle Credit Limited" },
  {
    value: "Volkswagen Financial Services (UK) Limited",
    label: "Volkswagen Financial Services (UK) Limited",
  },
  { value: "Whichdeal Ltd", label: "Whichdeal Ltd" },
];
